import { Tweet, TrendingTopic, SuggestedUser, Comment } from '@/types';

export const mockTweets: Tweet[] = [
  {
    id: '1',
    user: {
      id: '1',
      name: 'John Doe',
      username: 'johndoe',
      avatar: '',
      verified: true,
    },
    content: 'Just launched my new project! Excited to share it with everyone. 🚀',
    timestamp: '2h',
    likes: 124,
    retweets: 45,
    replies: 12,
  },
  {
    id: '2',
    user: {
      id: '2',
      name: 'Jane Smith',
      username: 'janesmith',
      avatar: '',
    },
    content: 'Beautiful sunset today! Nature never fails to amaze me. 🌅',
    timestamp: '4h',
    images: ['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
    likes: 892,
    retweets: 234,
    replies: 56,
  },
  {
    id: '3',
    user: {
      id: '3',
      name: 'Tech Enthusiast',
      username: 'techguru',
      avatar: '',
      verified: true,
    },
    content: 'The future of web development is looking bright with Next.js 14 and React Server Components!',
    timestamp: '6h',
    likes: 345,
    retweets: 123,
    replies: 34,
  },
  {
    id: '4',
    user: {
      id: '4',
      name: 'Designer Pro',
      username: 'designpro',
      avatar: '',
    },
    content: 'Minimalism is not about having less. It\'s about having exactly what you need.',
    timestamp: '8h',
    likes: 567,
    retweets: 189,
    replies: 78,
  },
  {
    id: '5',
    user: {
      id: '5',
      name: 'Alex Rivera',
      username: 'alexr',
      avatar: '',
      verified: true,
    },
    content: 'Working on something exciting! Can\'t wait to share it with you all. Stay tuned! 🎉',
    timestamp: '10h',
    likes: 234,
    retweets: 67,
    replies: 23,
  },
  {
    id: '6',
    user: {
      id: '6',
      name: 'Sarah Johnson',
      username: 'sarahj',
      avatar: '',
      verified: true,
    },
    content: 'Just finished reading an amazing book. Highly recommend it to everyone! 📚',
    timestamp: '12h',
    likes: 189,
    retweets: 45,
    replies: 12,
  },
  {
    id: '7',
    user: {
      id: '7',
      name: 'Mike Chen',
      username: 'mikechen',
      avatar: '',
    },
    content: 'Coffee and code - the perfect combination for a productive day ☕💻',
    timestamp: '14h',
    likes: 312,
    retweets: 89,
    replies: 34,
  },
  {
    id: '8',
    user: {
      id: '8',
      name: 'Emma Wilson',
      username: 'emmaw',
      avatar: '',
      verified: true,
    },
    content: 'The best way to predict the future is to create it. Let\'s build something amazing! ✨',
    timestamp: '16h',
    likes: 456,
    retweets: 123,
    replies: 45,
  },
  {
    id: '9',
    user: {
      id: '9',
      name: 'David Martinez',
      username: 'davidm',
      avatar: '',
      verified: true,
    },
    content: 'Just shipped a new feature that our users have been asking for. Excited to see their reactions! 🎊',
    timestamp: '18h',
    likes: 678,
    retweets: 234,
    replies: 89,
  },
  {
    id: '10',
    user: {
      id: '10',
      name: 'Lisa Anderson',
      username: 'lisaa',
      avatar: '',
    },
    content: 'Morning walk in the park. Sometimes you need to disconnect to reconnect. 🌳',
    timestamp: '20h',
    images: ['https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800'],
    likes: 234,
    retweets: 56,
    replies: 23,
  },
  {
    id: '11',
    user: {
      id: '11',
      name: 'Chris Thompson',
      username: 'christ',
      avatar: '',
      verified: true,
    },
    content: 'TypeScript + React = ❤️. The developer experience is unmatched!',
    timestamp: '22h',
    likes: 567,
    retweets: 189,
    replies: 67,
  },
  {
    id: '12',
    user: {
      id: '12',
      name: 'Maria Garcia',
      username: 'mariag',
      avatar: '',
    },
    content: 'Learning something new every day. That\'s what keeps life interesting! 📖',
    timestamp: '1d',
    likes: 189,
    retweets: 45,
    replies: 12,
  },
  {
    id: '13',
    user: {
      id: '13',
      name: 'James Brown',
      username: 'jamesb',
      avatar: '',
      verified: true,
    },
    content: 'The only way to do great work is to love what you do. Passion drives excellence! 🔥',
    timestamp: '1d',
    likes: 789,
    retweets: 234,
    replies: 89,
  },
  {
    id: '14',
    user: {
      id: '14',
      name: 'Sophie Lee',
      username: 'sophiel',
      avatar: '',
    },
    content: 'Weekend vibes: good music, great company, and amazing food! 🎵🍕',
    timestamp: '1d',
    likes: 345,
    retweets: 78,
    replies: 34,
  },
  {
    id: '15',
    user: {
      id: '15',
      name: 'Ryan Taylor',
      username: 'ryant',
      avatar: '',
      verified: true,
    },
    content: 'Just discovered an incredible new tool that\'s going to change my workflow. Game changer! 🚀',
    timestamp: '1d',
    likes: 456,
    retweets: 123,
    replies: 45,
  },
  {
    id: '16',
    user: {
      id: '16',
      name: 'Olivia White',
      username: 'oliviaw',
      avatar: '',
    },
    content: 'Sometimes the best ideas come when you least expect them. Keep your mind open! 💡',
    timestamp: '1d',
    likes: 234,
    retweets: 56,
    replies: 23,
  },
  {
    id: '17',
    user: {
      id: '17',
      name: 'Daniel Kim',
      username: 'danielk',
      avatar: '',
      verified: true,
    },
    content: 'Code review done. Time to merge and deploy! 🚢',
    timestamp: '1d',
    likes: 123,
    retweets: 34,
    replies: 12,
  },
  {
    id: '18',
    user: {
      id: '18',
      name: 'Amanda Davis',
      username: 'amandad',
      avatar: '',
    },
    content: 'The sunset tonight was absolutely breathtaking. Nature\'s art at its finest! 🌇',
    timestamp: '1d',
    images: ['https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=800'],
    likes: 567,
    retweets: 189,
    replies: 67,
  },
  {
    id: '19',
    user: {
      id: '19',
      name: 'Kevin Park',
      username: 'kevinp',
      avatar: '',
      verified: true,
    },
    content: 'Debugging is like being a detective in a crime movie where you\'re also the murderer 🕵️',
    timestamp: '2d',
    likes: 890,
    retweets: 345,
    replies: 123,
  },
  {
    id: '20',
    user: {
      id: '20',
      name: 'Rachel Green',
      username: 'rachelg',
      avatar: '',
    },
    content: 'New week, new goals, new opportunities. Let\'s make it count! 💪',
    timestamp: '2d',
    likes: 234,
    retweets: 67,
    replies: 23,
  },
  {
    id: '21',
    user: {
      id: '21',
      name: 'Tom Wilson',
      username: 'tomw',
      avatar: '',
      verified: true,
    },
    content: 'Just hit 10K followers! Thank you all for the amazing support. This community is incredible! 🎉',
    timestamp: '2d',
    likes: 1234,
    retweets: 456,
    replies: 189,
  },
  {
    id: '22',
    user: {
      id: '22',
      name: 'Nina Patel',
      username: 'ninap',
      avatar: '',
    },
    content: 'Morning meditation session complete. Starting the day with clarity and focus 🧘‍♀️',
    timestamp: '2d',
    likes: 345,
    retweets: 89,
    replies: 34,
  },
  {
    id: '23',
    user: {
      id: '23',
      name: 'Carlos Rodriguez',
      username: 'carlosr',
      avatar: '',
      verified: true,
    },
    content: 'The best code is code that you don\'t have to write. Simplicity wins! 🎯',
    timestamp: '2d',
    likes: 678,
    retweets: 234,
    replies: 89,
  },
  {
    id: '24',
    user: {
      id: '24',
      name: 'Zoe Mitchell',
      username: 'zoem',
      avatar: '',
    },
    content: 'Weekend project: building a personal dashboard. Learning by doing! 📊',
    timestamp: '2d',
    likes: 234,
    retweets: 56,
    replies: 23,
  },
  {
    id: '25',
    user: {
      id: '25',
      name: 'Ben Foster',
      username: 'benf',
      avatar: '',
      verified: true,
    },
    content: 'Just watched an incredible documentary. Always inspiring to learn about people pushing boundaries! 🎬',
    timestamp: '3d',
    likes: 456,
    retweets: 123,
    replies: 45,
  },
  {
    id: '26',
    user: {
      id: '26',
      name: 'Luna Chen',
      username: 'lunac',
      avatar: '',
    },
    content: 'Coffee shop coding session. There\'s something about the ambient noise that helps me focus ☕',
    timestamp: '3d',
    likes: 345,
    retweets: 78,
    replies: 34,
  },
  {
    id: '27',
    user: {
      id: '27',
      name: 'Sam Johnson',
      username: 'samj',
      avatar: '',
      verified: true,
    },
    content: 'Refactored 500 lines of code today. It\'s not just about making it work, it\'s about making it right! ✨',
    timestamp: '3d',
    likes: 567,
    retweets: 189,
    replies: 67,
  },
  {
    id: '28',
    user: {
      id: '28',
      name: 'Maya Singh',
      username: 'mayas',
      avatar: '',
    },
    content: 'The power of a good night\'s sleep cannot be underestimated. Rest is productive! 😴',
    timestamp: '3d',
    likes: 234,
    retweets: 56,
    replies: 23,
  },
  {
    id: '29',
    user: {
      id: '29',
      name: 'Jack Miller',
      username: 'jackm',
      avatar: '',
      verified: true,
    },
    content: 'Just open-sourced a project I\'ve been working on. Excited to see what the community does with it! 🌟',
    timestamp: '3d',
    likes: 890,
    retweets: 345,
    replies: 123,
  },
  {
    id: '30',
    user: {
      id: '30',
      name: 'Ava Thompson',
      username: 'avat',
      avatar: '',
    },
    content: 'Sometimes you need to step back to see the bigger picture. Perspective is everything! 🎨',
    timestamp: '3d',
    images: ['https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800'],
    likes: 456,
    retweets: 123,
    replies: 45,
  },
];

export const mockTrendingTopics: TrendingTopic[] = [
  {
    id: '1',
    title: 'Web Development',
    category: 'Technology',
    tweetCount: '125K',
  },
  {
    id: '2',
    title: 'Design Trends',
    category: 'Design',
    tweetCount: '89K',
  },
  {
    id: '3',
    title: 'Next.js',
    category: 'Technology',
    tweetCount: '45K',
  },
  {
    id: '4',
    title: 'UI/UX',
    category: 'Design',
    tweetCount: '67K',
  },
];

export const mockSuggestedUsers: SuggestedUser[] = [
  {
    id: '1',
    name: 'Sarah Johnson',
    username: 'sarahj',
    avatar: '',
    verified: true,
  },
  {
    id: '2',
    name: 'Mike Chen',
    username: 'mikechen',
    avatar: '',
  },
  {
    id: '3',
    name: 'Emma Wilson',
    username: 'emmaw',
    avatar: '',
    verified: true,
  },
  {
    id: '4',
    name: 'David Martinez',
    username: 'davidm',
    avatar: '',
    verified: true,
  },
  {
    id: '5',
    name: 'Lisa Anderson',
    username: 'lisaa',
    avatar: '',
  },
  {
    id: '6',
    name: 'Chris Thompson',
    username: 'christ',
    avatar: '',
    verified: true,
  },
  {
    id: '7',
    name: 'Maria Garcia',
    username: 'mariag',
    avatar: '',
  },
  {
    id: '8',
    name: 'James Brown',
    username: 'jamesb',
    avatar: '',
    verified: true,
  },
  {
    id: '9',
    name: 'Sophie Lee',
    username: 'sophiel',
    avatar: '',
  },
  {
    id: '10',
    name: 'Ryan Taylor',
    username: 'ryant',
    avatar: '',
    verified: true,
  },
  {
    id: '11',
    name: 'Olivia White',
    username: 'oliviaw',
    avatar: '',
  },
  {
    id: '12',
    name: 'Daniel Kim',
    username: 'danielk',
    avatar: '',
    verified: true,
  },
  {
    id: '13',
    name: 'Amanda Davis',
    username: 'amandad',
    avatar: '',
  },
  {
    id: '14',
    name: 'Kevin Park',
    username: 'kevinp',
    avatar: '',
    verified: true,
  },
  {
    id: '15',
    name: 'Rachel Green',
    username: 'rachelg',
    avatar: '',
  },
];

export const mockComments: Comment[] = [
  {
    id: '1',
    user: {
      id: '6',
      name: 'Alex Rivera',
      username: 'alexr',
      avatar: '',
      verified: true,
    },
    content: 'This is amazing! Great work! 🎉',
    timestamp: '1h',
    likes: 45,
    replies: 3,
    tweetId: '1',
  },
  {
    id: '2',
    user: {
      id: '7',
      name: 'Sarah Johnson',
      username: 'sarahj',
      avatar: '',
      verified: true,
    },
    content: 'Congratulations on the launch! Looking forward to seeing more.',
    timestamp: '1.5h',
    likes: 32,
    replies: 1,
    tweetId: '1',
  },
  {
    id: '3',
    user: {
      id: '8',
      name: 'Mike Chen',
      username: 'mikechen',
      avatar: '',
    },
    content: 'Can you share more details about the tech stack?',
    timestamp: '2h',
    likes: 18,
    replies: 0,
    tweetId: '1',
  },
  {
    id: '4',
    user: {
      id: '9',
      name: 'Emma Wilson',
      username: 'emmaw',
      avatar: '',
      verified: true,
    },
    content: 'This looks incredible! Well done! 👏',
    timestamp: '2.5h',
    likes: 67,
    replies: 2,
    tweetId: '1',
  },
  {
    id: '5',
    user: {
      id: '10',
      name: 'David Martinez',
      username: 'davidm',
      avatar: '',
      verified: true,
    },
    content: 'Excited to try this out! When will it be available?',
    timestamp: '3h',
    likes: 29,
    replies: 1,
    tweetId: '1',
  },
];
